/*
 * @File Serve.java
 * @Authors : David González León, Jade Gröli, Axel Vallon
 * @Date 5 mars 2021
 */
package ch.heigvd.VallonGroeliGonzalezLeon.statique.command;

import picocli.CommandLine;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.Callable;

@CommandLine.Command(
        name = "serve", mixinStandardHelpOptions = true, description = "open the index.html file in the build file in default browser. This command " +
        "needs to be executed at the root of the directory generated by the init command.\n " +
        "In case of error the command will return 2\n"
)
public class Serve implements Callable<Integer> {

   @Override
   public Integer call() {
   File currentDirectory;
   try {
      currentDirectory = new File(new File(".").getCanonicalPath() + "\\build\\index.html");
      Desktop.getDesktop().browse(currentDirectory.toURI());
   } catch (IOException e) {
      System.err.println("Error while reading current directory");
      e.printStackTrace();
      return 2;
   }
      return 0;
   }


}
